---
vector_version: "0.45.0"
vector_architecture: "arm"
vector_data_dir: "/var/lib/vector"
vector_encoding_codec: "json"
vector_sources:
  internal_metrics:
    type: "internal_metrics"
vector_sinks:
  console:
    type: "console"
    inputs: ["internal_metrics"]
    encoding:
      codec: "{{ vector_encoding_codec }}"