apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Netology K8s Lab 2.3</title>
    </head>
    <body>
      <h1>Hello from Kubernetes ConfigMap!</h1>
      <p>Задание 1: ConfigMap подключён как Volume</p>
    </body>
    </html>
