apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: netology-web
spec:
  containers:
    - name: echoserver
      image: ret97/echoserver-arm:2.2
      ports:
        - containerPort: 8080