---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 89.169.129.207
      ansible_user: avryahov
vector:
  hosts:
    vector-01:
      ansible_host: 89.169.148.206
      ansible_user: avryahov
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.78.162
      ansible_user: avryahov