---
# Параметры Nginx
nginx_mime_types: "/etc/nginx/mime.types"
nginx_default_type: "application/octet-stream"

# Логирование
nginx_access_log_path: "/var/log/nginx/my_access.log"
nginx_access_log_format: "combined"

# Настройки сервера
nginx_listen_port: 80
nginx_server_name: "localhost"
nginx_root_dir: "/usr/share/nginx/html"
nginx_index_files:
  - "index.html"
  - "index.htm"

# Дополнительные параметры
nginx_sendfile: "on"
nginx_keepalive_timeout: 65