#SPDX-License-Identifier: MIT-0
---
- name: Create database {{ clickhouse_database }}
  ansible.builtin.command: >
    clickhouse-client --host=127.0.0.1 -q "CREATE DATABASE IF NOT EXISTS {{ clickhouse_database }};"

- name: Create table {{ clickhouse_table }}
  ansible.builtin.command: >
    clickhouse-client --host=127.0.0.1 -q "
    CREATE TABLE IF NOT EXISTS {{ clickhouse_database }}.{{ clickhouse_table }} (
      timestamp String,
      level String,
      message String
    ) ENGINE = MergeTree()
    ORDER BY tuple(timestamp);"
