#SPDX-License-Identifier: MIT-0
---
- name: Wait for ClickHouse to become available
  ansible.builtin.command: "clickhouse-client -q 'SELECT 1'"
  register: ch_ready
  retries: 10
  delay: 3
  until: ch_ready.rc == 0
  changed_when: false

- name: Create database {{ clickhouse_database }}
  ansible.builtin.command: >
    clickhouse-client -q "CREATE DATABASE IF NOT EXISTS {{ clickhouse_database }};"

- name: Create table {{ clickhouse_table }}
  ansible.builtin.command: >
    clickhouse-client -q "
    CREATE TABLE IF NOT EXISTS {{ clickhouse_database }}.{{ clickhouse_table }} (
      timestamp String,
      level String,
      message String
    ) ENGINE = MergeTree()
    ORDER BY tuple(timestamp);"
