---
- name: Build Docker images for ClickHouse and Vector
  hosts: localhost
  vars_files:
    - group_vars/all/vars.yml
  tasks:
    - name: Debug decrypted password
      debug:
        msg: "Decrypted password is {{ common_password }}"

    - name: Build Docker image for ClickHouse
      command: >
        docker build
        --build-arg ROOT_PASSWORD="{{ common_password }}"
        -t clickhouse-host .
      args:
        chdir: ./base  # Путь к Dockerfile

    - name: Build Docker image for Vector
      command: >
        docker build
        --build-arg ROOT_PASSWORD="{{ common_password }}"
        -t vector-host .
      args:
        chdir: ./base  # Путь к Dockerfile